package com.bonifacio.urls_ripper.services;

import com.bonifacio.urls_ripper.dtos.UrlDto;
import com.bonifacio.urls_ripper.dtos.UrlUserDto;
import com.bonifacio.urls_ripper.dtos.UrlsDetails;
import com.bonifacio.urls_ripper.encode.UrlEncode;
import com.bonifacio.urls_ripper.entities.Url;
import com.bonifacio.urls_ripper.entities.UserUrl;
import com.bonifacio.urls_ripper.mappers.UrlMapper;
import com.bonifacio.urls_ripper.repositories.UrlRepository;
import com.bonifacio.urls_ripper.repositories.UrlUserRepository;
import com.bonifacio.urls_ripper.repositories.UserRepository;
import lombok.AllArgsConstructor;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;

import static com.google.common.hash.Hashing.murmur3_32;

@AllArgsConstructor
@Component
public class UrlsServiceImplement implements UrlService {
    @Autowired
    private final UrlRepository _urlRepository;
    @Autowired
    private final JwtService _jwtService;
    @Autowired
    private final UrlUserRepository _urlUserRepository;
    @Autowired
    private final UserRepository _userRepository;
    @Autowired
    private  final UrlEncode _urlEncode;
    @Autowired
    private final UrlMapper _urlMapper;
    @Autowired
    private final DateCal _dateCal;
    /**
     * The `generateSlug` function takes a `UrlDto` object, encodes the URL, creates
     * a new `Url` object
     * with the encoded URL as the slug, sets the creation and expiration dates, and
     * returns the `Url`
     * object.
     * 
     * @param urlDto The `urlDto` parameter is an object of type `UrlDto` which
     *               contains the following
     *               properties:
     * @return The method is returning an object of type Url.
     */
    @Override
    public Url generateSlug(UrlDto urlDto) {
        if (StringUtils.isEmpty(urlDto.url())) {
            return null;
        }
        String encodeUrl = _urlEncode.urlEncode(urlDto.url());
        Url urlPersistence = _urlMapper.urlDtoToUrl(urlDto);
        urlPersistence
                .setExpirationData(_dateCal.getExpirationData(urlDto.expirationDate(), urlPersistence.getCreationData()));
        urlPersistence.setSlug(encodeUrl);
        if (StringUtils.isEmpty(encodeUrl))
            return null;

        return urlPersistence;
    }

    /**
     * @param urlUserDto
     * @param token
     * @return
     */
    /**
     * The function generates a user slug based on input data and a token, creating
     * a UserUrl object
     * with the encoded URL and other details.
     * 
     * @param urlUserDto The `urlUserDto` parameter is an object that contains
     *                   information about a
     *                   user's URL, such as the URL itself, the name of the URL, a
     *                   description, and an expiration date.
     *                   It is used to generate a user slug for the given URL.
     * @param token      A token is a piece of data that is used to authenticate a
     *                   user and grant access to
     *                   a system or application. It is typically generated by the
     *                   system upon successful login and is
     *                   used to identify the user in subsequent requests. In the
     *                   context of the code snippet you
     *                   provided, the token is likely being used
     * @return The method `generateUserSlug` returns a `UserUrl` object, which
     *         contains information
     *         such as the link, name, slug, user, description, creation date, and
     *         expiration date.
     */
    @Override
    public UserUrl generateUserSlug(UrlUserDto urlUserDto, String token) {
        if (StringUtils.isEmpty(token) || StringUtils.isEmpty(urlUserDto.url())) {
            return null;
        }
        var username = _jwtService.getUsernameFromToken(token);
        var user = _userRepository.findByUsername(username);
        if (user.isEmpty()) {
            return null;
        }
        var slug = _urlEncode.urlEncode(urlUserDto.url());
        if (StringUtils.isEmpty(slug))
            return null;
        var url = _urlMapper.urlUserDtoToUserUrl(urlUserDto);
        url.setSlug(slug);
        url.setUser(user.get());
        url.setExpirationData(_dateCal.getExpirationData(urlUserDto.expirationDate(), url.getCreationData()));
        return url;
    }



    @Override
    public Url persitenstUrl(Url url) {

        return _urlRepository.save(url);
    }

    /**
     * @param userUrl
     * @return
     */
    @Override
    public UserUrl persitestUserUrl(UserUrl userUrl) {

        return _urlUserRepository.save(userUrl);
    }

    /**
     * The function `getEncodeUrl` returns a Url object based on the provided slug.
     * 
     * @param url The `url` parameter in the `getEncodeUrl` method is a String
     *            representing the URL that
     *            you want to encode or retrieve from the `_urlRepository` based on
     *            a given slug.
     * @return The method `getEncodeUrl` is returning a `Url` object, which is
     *         retrieved from the
     *         `_urlRepository` by searching for a slug that matches the input
     *         `url`.
     */
    @Override
    public Url getEncodeUrl(String url) {
        return _urlRepository.findBySlug(url);
    }

    /**
     * @param id 
     * @return
     */
    @Override
    public UrlsDetails getUserUrlById(String id) {
        var url = _urlUserRepository.findBySlug(id);
        return _urlMapper.userUrlToUserDetails(url);
    }

    @Override
    public void deleteSlug(Url url) {
        var res = _urlUserRepository.findById(url.getId());
        if(res.isEmpty()) {
            var resU = _urlRepository.findById(url.getId()).orElseThrow();
            _urlRepository.delete(resU);

        }else {
            _urlUserRepository.delete(res.get());
        }
    }

    /**
     * @param slug
     * @return
     */
    @Override
    public UrlsDetails updateUserUrl(String slug,UrlUserDto userDto) {
        var oldUrl = _urlUserRepository.findBySlug(slug);
        if(oldUrl.isEmpty()){
            return null;
        }
        oldUrl.get().setName(userDto.name());
        oldUrl.get().setDescription(userDto.description());
        oldUrl.get().setExpirationData(_dateCal.getExpirationData(userDto.expirationDate(),oldUrl.get().getExpirationData()));
        _urlUserRepository.save(oldUrl.get());
        return _urlMapper.userUrlToUserDetails(oldUrl);
    }
}
